### PR TITLE
Add ability to specify a mixins array for stores

### PR DESCRIPTION
**Pull request by lelandrichardson**
Adding logic to import mixins through a `mixins` array, similar to react components.

This was discussed in more detail [here](https://github.com/kjda/ReactFlux/issues/4)

### CODE REVIEW

**Comment by lelandrichardson** [comment]
I just thought of something for this. It's possible that a mixin could require specific behavior for certain lifecycle events such as `getInitialState` and `storeDidMount`.

I think if multiple mixins are used that implement these lifecycle events, it should be handled properly... (rather than just overriding their own implementations, as this version would do currently)

what do you think?

I don't have time to implement this tonight, but could push an update tomorrow.

**Comment by lelandrichardson** [comment]
well, I lied. I did have time to implement this...

Let me know what you think!

**Comment by lelandrichardson** [comment]
@kjda Let me know if there's anything you want me to change with this to get it merged. Thanks.

**Comment by kjda** [comment]
thanks man! great :)

**Pull request merged**
